### ISSUE TITLE
importing `makeEdgeEnv` interferes with `@cloudflare/workers-types` typings

### ISSUE THREAD

**Issue by toinbis** [samuelcolvin/edge-mock#12]
Starting using edge-mock in one of the projects. Enjoying it much.

I came across and odd situation, which might be totally expected, but I felt like reporting it as potential issue nonetheless.

I was successfully using `ModuleWorker` typings from https://github.com/cloudflare/workers-types/blob/feat/module-worker/index.d.ts#L734 (installed `@cloudflare/workers-types` from git branch).

The moment I starting writing my test, and did this by adding `import { makeEdgeEnv } from 'edge-mock'` as first line to my initial test, this TS error started popping out.

![Screenshot 2021-08-22 at 22 46 08](https://user-images.githubusercontent.com/68685/130368172-7fda2093-d45d-41a8-b7ec-3462ff244455.png)

I can silence the error by either of:
a) Commenting out `import { makeEdgeEnv } from 'edge-mock'`  (which I sure don't wan't to do);
b) Commenting out `"tests/*.ts"` from tsconfig.json's `include` values (which I'm not sure I want to do);

Either `a)` or `b)` brings back expected typings:
![Screenshot 2021-08-22 at 22 59 52](https://user-images.githubusercontent.com/68685/130368406-6d1a6339-6e56-4c06-8ee1-5094e4947934.png)

Maybe it's just `b)` - I am supposed to exclude tests from "include" in tsconfig.json. Maybe it's edge-mock not (yet) supporting Modules syntax. Or maybe anything else that my limited knowledge/expertise does not allow me to identify, that causes this TS error.

Kindly please feel free to instantly close this issue if that's an expected behaviour. Thanks!

**Comment by toinbis** [comment]
Rewrote repo from scratch and the issue seems to be gone. Sorry for false alarm. Am closing the issue.

**Comment by samuelcolvin** [comment]
Pleased you sorted it.
