### ISSUE TITLE
CF Crypto

### ISSUE THREAD

**Issue by carlsonorozco** [samuelcolvin/edge-mock#8]
Hi @samuelcolvin,

Great work with edge-mock. I was wondering how I can do a test with CF Crypto although got some error while importing crypto lib

```
Error - TypeError: Cannot read property 'importKey' of undefined
```

**Comment by samuelcolvin** [comment]
Well, you need to mock `crypto` which edge-mock doesn't do.

If you're using node 16, you should be able to use the [`webcrypto`](https://nodejs.org/api/webcrypto.html#webcrypto_examples) interface.

If you're using earlier node, you can use the `node-webcrypto-ossl` package.

Here's a simple example of installing `crypto` and using it:

```ts
import {Crypto as WebCrypto} from 'node-webcrypto-ossl'
import {makeEdgeEnv} from 'edge-mock'

describe('handleRequest', () => {
  beforeEach(() => {
    const crypto = new WebCrypto({directory: 'key_storage'})
    makeEdgeEnv({crypto})
    jest.resetModules()
  })

  test('crypto', async () => {
    const keyPair = await crypto.subtle.generateKey(
      {
        name: 'ECDSA',
        namedCurve: 'P-384',
      },
      true,
      ['sign', 'verify'],
    )
    console.log('keyPair:', keyPair)
  })
})
```

Let me know how you get on.

**Comment by carlsonorozco** [comment]
Hi @samuelcolvin,

The code above works and I'm using the LTS (14.17.1). Thank you!

Got another error :| `InternalError [KVError]: there is no KV namespace bound to the script`. Could you share some thought on how to add KV.

**Comment by samuelcolvin** [comment]
```ts
import {makeEdgeEnv, EdgeKVNamespace} from 'edge-mock'

const kv_namespace = new EdgeKVNamespace()

describe('handle', () => {
  beforeEach(() => {
    kv_namespace._clear()
    kv_namespace._putMany({
      ... // put initial things
    })
    makeEdgeEnv({WHATEVER_KV_IS_CALLED: kv_namespace})
  })

  ...
})
```

Something like this should work, let me know if not. (I need to do proper docs)

**Comment by carlsonorozco** [comment]
Hi @samuelcolvin,

Thanks for this. Apparently, my workers include workers-site is now looking for a file inside ASSET_NAMESPACE. I roaming around the issues with kv-asset-handler. Do you have an idea how we can achieve this?

**Comment by samuelcolvin** [comment]
yes I sure do :smile: 

```ts
makeEdgeEnv({
  WHATEVER_KV_IS_CALLED: kv_namespace, 
  ASSET_NAMESPACE: kv_namespace._manifestJson(),
})
```

I'm using wrangler sites so already built support for this.

**Comment by samuelcolvin** [comment]
Oh sorry, got it slightly wrong. If you're using wrangler sites, you need the following.

```ts
makeEdgeEnv({
  __STATIC_CONTENT: kv_namespace, 
  __STATIC_CONTENT_MANIFEST: kv_namespace._manifestJson(),
})
```

There are some examples in `src/server.ts`.

**Comment by carlsonorozco** [comment]
Hi @samuelcolvin got an error `there is no KV namespace bound to the script` https://github.com/cloudflare/kv-asset-handler/blob/3d4ac8ee120656c31ce56ee2aa8aece1abff5d17/src/index.ts#L113 🤔

**Comment by samuelcolvin** [comment]
This is a separate issue, please create new issues for each distinct problem you have. Also please include a self-contained demo of the issue you're having.

I'm not responsible for `kv-asset-handler`, but it looks like you're not setting the global name `__STATIC_CONTENT` to anything. See my answer above.

**Comment by cpbotha** [comment]
Just in case someone else could use a hint as to how to mock in Node 16's webcrypto as suggested by @samuelcolvin -- the following does the trick:

```typescript
describe('someFuncToTest', () => {
  beforeEach(() => {
    // remember to install @types/node
    const nodeCrypto = require('crypto')
    global.crypto = nodeCrypto.webcrypto
  })
  test('misc', () => {
    expect(someCryptoThing()).toEqual(42)
  })
})

```
